app/models.py
from app import db
from app import get_indian_time

class User(db.Model):
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(100),unique=True,nullable=False)
    password = db.Column(db.String(20),nullable= False)
    created_at = db.Column(db.DateTime, default=get_indian_time)
    last_login = db.Column(db.DateTime)

    # one-to-many relationship

    tasks = db.relationship('Task',backref='user',lazy=True)


class Task(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(100),nullable=False)
    status = db.Column(db.String(20),default="Pending")
    created_at = db.Column(db.DateTime, default=get_indian_time)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import pytz

IST = pytz.timezone('Asia/Kolkata')

def get_indian_time():
    return datetime.now(IST)


# create database obj globally 
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = 'your-secret-key'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///todo.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)

    from app.routes.auth import auth_bp
    from app.routes.tasks import tasks_bp
    app.register_blueprint(auth_bp)
    app.register_blueprint(tasks_bp)

    return app

app/routes/auth.py
from flask import Blueprint,render_template,request,redirect,url_for,flash,session
from app.models import User
from app import db,get_indian_time

auth_bp  = Blueprint('auth', __name__)



@auth_bp.route('/login',methods = ["GET","POST"])
def login():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username,password=password).first()

        if user:
            session['user'] = username
            user.last_login = get_indian_time()
            db.session.commit()
            flash("Login Successful",'success')
            return redirect(url_for('tasks.view_tasks'))
        else:
            flash("Invalid username or password ",'danger')

    return render_template('login.html')



@auth_bp.route('/signup',methods=["GET","POST"])
def signup():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')
        
        user = User.query.filter_by(username=username).first()

        if not user:
            new_user = User(username=username,password=password)
            db.session.add(new_user)
            db.session.commit()
            flash('Signup successful! You can now log in.', 'success')
            return redirect(url_for('auth.login'))
        else:
            flash("Username is already Exists",'danger')

    return render_template('signup.html')



@auth_bp.route('/logout')
def logout():
    session.pop("user",None)
    flash('Logged out ','info')
    return redirect(url_for('auth.login'))

app/routes/tasks.py
from flask import Blueprint,render_template,request,redirect,url_for,flash,session
from app import db,get_indian_time
from app.models import Task,User


tasks_bp = Blueprint('tasks',__name__)


@tasks_bp.route("/")
def view_tasks():
    if 'user' not in session:
        return redirect(url_for('auth.login'))
    
    user = User.query.filter_by(username=session['user']).first()
    tasks = user.tasks

    # tasks = Task.query.filter_by(username=session['user']).all()
    return render_template('tasks.html',tasks=tasks,name=user.username)


@tasks_bp.route('/add',methods = ["POST"])
def add_tasks():
    if 'user' not in session:
        return redirect(url_for('app.login'))
    
    title = request.form.get('title')
    if title:
        user_id = User.query.filter_by(username=session['user']).first().id
        new_task = Task(title=title,status='Pending',user_id=user_id,created_at=get_indian_time())
        db.session.add(new_task)
        db.session.commit()
        flash("Task Added successfully ",'success')

    return redirect(url_for('tasks.view_tasks'))

@tasks_bp.route('/toggle/<int:task_id>',methods=["POST"])
def toggle_status(task_id):
    if 'user' not in session:
        return redirect(url_for('app.login'))
    
    task = Task.query.get(task_id)
    if task:
        if task.status == "Pending":
            task.status = "Working"
        elif task.status == "Working":
            task.status = "Done"
        else:
            task.status = "Pending"
        db.session.commit()
    return redirect(url_for('tasks.view_tasks'))


@tasks_bp.route('/delete-task/<int:task_id>',methods = ["POST"])
def delete_task(task_id):
    if 'user' not in session:
        return redirect(url_for('app.login'))
    
    task = Task.query.filter_by(id=task_id).first()
    if task:
        db.session.delete(task)
        db.session.commit()
        flash("Task Deleted successfully.",'success')
    else:
        flash("Task not found or unauthorized.", "error")
    return redirect(url_for('tasks.view_tasks'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header>
        <div class="container">
            <h1>My To-Do APP</h1><br>
            <nav>
                <a href="{{url_for('tasks.view_tasks')}}">Home</a>
                {% if 'user' in session %}
                  <a href="{{url_for('auth.logout')}}">Logout</a>
                {% else %}
                  <a href="{{url_for('auth.login')}}">Login</a>
                {% endif %}
            </nav>
        </div>
    </header>
    
    <main class="container">

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% for category,message in messages %}
                <div class="flash {{category}}">{{message}}</div>
            {% endfor %}
        {% endwith %}  

        {% block body %}
          
        {% endblock body %}

    </main>

    <footer>
        <div class="container">
            <p>&copy; 2025 My Flask To-Do App</p>
        </div>
    </footer>

</body>
</html>

app/templates/login.html
{% extends "base.html" %}

{% block title %}
Login Page
{% endblock title %}

{% block body %}

  <div class="login-box">
    <h2>Login User </h2>
    <form method="post">
      
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" name="username" id="username" required>
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required>
      </div>
      
      <button type="submit" class="btn">Login</button>

    </form>
    <br>
    <a class="link" href="{{ url_for('auth.signup') }}">New user? Signup here</a>
  </div>

{% endblock body %}

app/templates/signup.html
{% extends "base.html" %}

{% block title %}
Sign Up Page
{% endblock title %}

{% block body %}

<div class="login-box">
    <h2>Signup User </h2>
    <form method="post">
      
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" name="username" id="username" required>
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required>
      </div>
      
      <button type="submit" class="btn">Signup</button>

    </form>
    <br>
    <a class="link" href="{{ url_for('auth.login') }}">Back to Login</a>
  </div>
{% endblock body %}

app/templates/tasks.html
{% extends "base.html" %}

{% block title %}
Task Page
{% endblock title %}

{% block body %}
    
    <div class="task-box">
        
        <h2>Hello , <span style="color: green;">{{name}}</span></h2>
        <h2 style="text-align: center;">Your Tasks </h2>
        <form method="post" action="{{url_for('tasks.add_tasks')}}" class="task-form">
            <input type="text" name="title" placeholder="New task" required>
            <button type="submit" class="btn">Add</button>
        </form>
        <br>
        
    {% if tasks %}
        <div class="task-list">
            {% for task in tasks %}
            <div class="task-card">
                <div class="task-header">
                    <strong>{{ task.title }}</strong>
                    <span class="badge {{ task.status|lower }}">{{ task.status }}</span>
                </div>
                <div class="task-meta">
                    <small>Created: {{ task.created_at.strftime('%d %B %Y %I:%M %p') }}</small>
                </div>
                <div class="task-actions">
                    <form action="{{ url_for('tasks.toggle_status', task_id=task.id) }}" method="post">
                        <button type="submit" class="btn-small">Update Task</button>
                    </form>
                    <form action="{{ url_for('tasks.delete_task', task_id=task.id) }}" method="post">
                        <button type="submit" class="btn-small delete-btn">Delete</button>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No Tasks yet. Add one Above!</p>
    {% endif %}
</div>

{% endblock body %}